import json
import os
from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Any, Dict, List, Optional

import streamlit as st
from dotenv import load_dotenv
from PIL import Image

from ci_utils import (
    CI_FORM_DEFAULTS,
    DEFAULT_TEMPLATE_KEY,
    export_ci_to_template,
    get_available_templates,
    join_name,
    parse_ci_notes,
    save_export_copy,
)
from gemini_client import analyze_image_with_gemini
from inventory_store import (
    create_ci_submission,
    get_record,
    list_records_by_status,
    list_records_for_user,
    load_records,
    update_record,
)


load_dotenv()


st.set_page_config(
    page_title="Enterprise Inspection Portal",
    page_icon="AI",
    layout="wide",
    initial_sidebar_state="expanded",
)


RATING_ORDER = ["very bad", "poor", "fair", "good", "very good", "excellent"]
RATING_COLORS = {
    "very bad": "#ef4444",
    "poor": "#f97316",
    "fair": "#f59e0b",
    "good": "#22c55e",
    "very good": "#14b8a6",
    "excellent": "#0ea5e9",
}
STATUS_COLORS = {
    "submitted_to_ao": "#2563eb",
    "generated_by_ao": "#9333ea",
    "submitted_to_officer": "#16a34a",
}
STATUS_LABELS = {
    "submitted_to_ao": "Pending AO Review",
    "generated_by_ao": "Generated by AO",
    "submitted_to_officer": "Sent to Officer",
}
TEMPLATE_OPTIONS = get_available_templates()


def inject_styles() -> None:
    st.markdown(
        """
        <style>
            .stApp {
                background:
                    radial-gradient(circle at top left, rgba(14, 116, 144, 0.16), transparent 28%),
                    radial-gradient(circle at top right, rgba(59, 130, 246, 0.14), transparent 26%),
                    linear-gradient(180deg, #07111f 0%, #0b1730 55%, #0a1324 100%);
                color: #f8fafc;
            }
            .stMarkdown, .stText, .stCaption, p, label, span, div {
                color: #e5edf8;
            }
            [data-testid="stSidebar"] {
                background: rgba(9, 16, 32, 0.96);
                border-right: 1px solid rgba(148, 163, 184, 0.18);
            }
            .stTextInput input, .stTextArea textarea, .stNumberInput input {
                background: rgba(15, 23, 42, 0.92) !important;
                color: #f8fafc !important;
                border: 1px solid rgba(148, 163, 184, 0.22) !important;
            }
            div[data-baseweb="select"] > div, div[data-baseweb="base-input"] > div {
                background: rgba(15, 23, 42, 0.92) !important;
                color: #f8fafc !important;
                border-color: rgba(148, 163, 184, 0.22) !important;
            }
            .hero {
                background: linear-gradient(135deg, rgba(15, 23, 42, 0.96), rgba(17, 24, 39, 0.92));
                border: 1px solid rgba(96, 165, 250, 0.18);
                border-radius: 24px;
                padding: 28px;
                margin-bottom: 18px;
                box-shadow: 0 24px 70px rgba(2, 6, 23, 0.38);
            }
            .hero h1 {
                margin: 0 0 10px 0;
                font-size: 2.2rem;
                color: #ffffff;
            }
            .hero p {
                margin: 0;
                color: #dbe7f7;
                line-height: 1.7;
                font-size: 1rem;
            }
            .metric-card, .panel-card, .record-card, .object-card {
                background: rgba(15, 23, 42, 0.88);
                border: 1px solid rgba(148, 163, 184, 0.20);
                border-radius: 18px;
                padding: 18px;
                box-shadow: 0 18px 48px rgba(2, 6, 23, 0.18);
            }
            .metric-card {
                min-height: 124px;
            }
            .metric-label {
                color: #c9d7ea;
                font-size: 0.82rem;
                text-transform: uppercase;
                letter-spacing: 0.08em;
                font-weight: 700;
            }
            .metric-value {
                color: #ffffff;
                font-size: 1.85rem;
                font-weight: 800;
                margin-top: 10px;
            }
            .metric-detail, .muted {
                color: #d7e3f4;
                margin-top: 8px;
                font-size: 0.96rem;
                line-height: 1.6;
            }
            .section-title {
                color: #ffffff;
                font-size: 1.05rem;
                font-weight: 700;
                margin: 0 0 8px 0;
            }
            .pill {
                display: inline-block;
                padding: 6px 10px;
                border-radius: 999px;
                font-size: 0.8rem;
                font-weight: 800;
                letter-spacing: 0.04em;
                text-transform: uppercase;
                color: white;
            }
            .note-box {
                background: rgba(8, 15, 30, 0.9);
                border: 1px solid rgba(59, 130, 246, 0.16);
                border-radius: 16px;
                padding: 16px;
                white-space: pre-wrap;
                line-height: 1.6;
                color: #f1f5f9;
            }
            .small {
                color: #c5d3e6;
                font-size: 0.9rem;
            }
        </style>
        """,
        unsafe_allow_html=True,
    )


def rating_badge(rating: str) -> str:
    normalized = (rating or "fair").strip().lower()
    color = RATING_COLORS.get(normalized, "#475467")
    return f'<span class="pill" style="background:{color};">{normalized}</span>'


def status_badge(status: str) -> str:
    color = STATUS_COLORS.get(status, "#475467")
    label = STATUS_LABELS.get(status, status.replace("_", " ").title())
    return f'<span class="pill" style="background:{color};">{label}</span>'


def render_metric(label: str, value: str, detail: str) -> None:
    st.markdown(
        f"""
        <div class="metric-card">
            <div class="metric-label">{label}</div>
            <div class="metric-value">{value}</div>
            <div class="metric-detail">{detail}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def to_label(value: str) -> str:
    return (value or "Unknown").replace("_", " ").title()


def get_secret(name: str, default: str = "") -> str:
    try:
        return str(st.secrets.get(name, default)).strip()
    except Exception:
        return default


def get_gemini_api_key() -> str:
    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    if api_key:
        return api_key
    return get_secret("GEMINI_API_KEY", "")


def get_users() -> Dict[str, Dict[str, str]]:
    ci_email = get_secret("CI_EMAIL", os.getenv("CI_EMAIL", "ci@company.com")).lower()
    ci_password = get_secret("CI_PASSWORD", os.getenv("CI_PASSWORD", "CI123456"))
    ao_email = get_secret("AO_EMAIL", os.getenv("AO_EMAIL", "janielsenador@gmail.com")).lower()
    ao_password = get_secret("AO_PASSWORD", os.getenv("AO_PASSWORD", "123456"))
    officer_email = get_secret("OFFICER_EMAIL", os.getenv("OFFICER_EMAIL", "officer@company.com")).lower()
    officer_password = get_secret("OFFICER_PASSWORD", os.getenv("OFFICER_PASSWORD", "Officer123!"))

    return {
        ci_email: {"password": ci_password, "role": "ci", "name": "CI Encoder"},
        ao_email: {"password": ao_password, "role": "ao", "name": "Account Officer"},
        officer_email: {"password": officer_password, "role": "officer", "name": "Senior Account Officer"},
    }


def init_form_state(prefix: str) -> None:
    for field_name, default_value in CI_FORM_DEFAULTS.items():
        st.session_state.setdefault(f"{prefix}_{field_name}", default_value)


def seed_form_state(prefix: str, values: Dict[str, Any]) -> None:
    for field_name in CI_FORM_DEFAULTS:
        st.session_state[f"{prefix}_{field_name}"] = values.get(field_name, "")


def collect_form_data(prefix: str) -> Dict[str, Any]:
    return {field_name: st.session_state.get(f"{prefix}_{field_name}", "") for field_name in CI_FORM_DEFAULTS}


def clear_form_state(prefix: str) -> None:
    for field_name, default_value in CI_FORM_DEFAULTS.items():
        st.session_state[f"{prefix}_{field_name}"] = default_value


def init_session_state() -> None:
    st.session_state.setdefault("auth_user", None)
    st.session_state.setdefault("ci_submit_notes", "")
    st.session_state.setdefault("ci_clear_submit_notes", False)
    st.session_state.setdefault("ao_selected_record_id", "")
    st.session_state.setdefault("ao_template_key", DEFAULT_TEMPLATE_KEY)
    st.session_state.setdefault("ao_export_bytes", b"")
    st.session_state.setdefault("ao_export_name", "")
    st.session_state.setdefault("ao_export_path", "")
    init_form_state("ao")


def logout() -> None:
    st.session_state["auth_user"] = None
    st.rerun()


def read_file_bytes(path_value: str) -> bytes:
    if not path_value:
        return b""
    path = Path(path_value)
    if not path.exists():
        return b""
    return path.read_bytes()


def format_record_title(record: Dict[str, Any]) -> str:
    applicant = record.get("applicant_name") or record.get("account_name") or "Unnamed Applicant"
    template = record.get("template_label") or "No Template"
    return f"{record.get('id')} | {applicant} | {STATUS_LABELS.get(record.get('status', ''), 'Pending')} | {template}"


def count_by_template(records: List[Dict[str, Any]], template_key: str) -> int:
    return sum(1 for record in records if record.get("template_key") == template_key)


def load_record_to_workspace(record: Dict[str, Any]) -> None:
    st.session_state["ao_selected_record_id"] = record["id"]
    st.session_state["ao_template_key"] = record.get("template_key") or DEFAULT_TEMPLATE_KEY
    seed_form_state("ao", record.get("parsed_data", parse_ci_notes(record.get("ci_notes", ""))))
    st.session_state["ao_export_name"] = record.get("generated_file_name", "")
    st.session_state["ao_export_path"] = record.get("generated_file_path", "")
    st.session_state["ao_export_bytes"] = read_file_bytes(record.get("generated_file_path", ""))


def render_login_page() -> None:
    st.markdown(
        """
        <div class="hero">
            <h1>Enterprise Inspection Portal</h1>
            <p>
                One portal, three roles. CI submits raw notes, AO converts notes into the correct
                PDRN workbook, and the Officer receives the generated file while keeping access
                to the AI Image Analyzer.
            </p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    col1, col2, col3 = st.columns(3)
    with col1:
        render_metric("CI Role", "Notes Only", "Credit Investigators submit field notes into the inventory queue.")
    with col2:
        render_metric("AO Role", "PDRN Builder", "Account Officers choose BPI or Maybank PDRN, generate, and submit.")
    with col3:
        render_metric("Officer Role", "Inbox + AI", "Officers receive generated PDRNs and run the image analyzer.")

    with st.form("login_form", clear_on_submit=False):
        email = st.text_input("Email")
        password = st.text_input("Password", type="password")
        submitted = st.form_submit_button("Sign In", type="primary", use_container_width=True)

    if not submitted:
        return

    users = get_users()
    user_record = users.get(email.strip().lower())
    if not user_record or user_record["password"] != password:
        st.error("Invalid email or password.")
        return

    st.session_state["auth_user"] = {
        "email": email.strip().lower(),
        "role": user_record["role"],
        "name": user_record["name"],
    }
    st.rerun()


def normalize_objects(result: Dict[str, Any]) -> List[Dict[str, Any]]:
    objects = result.get("objects", [])
    if isinstance(objects, list):
        return [item for item in objects if isinstance(item, dict)]
    return []


def summarize_objects(objects: List[Dict[str, Any]]) -> Dict[str, int]:
    counts = {rating: 0 for rating in RATING_ORDER}
    for item in objects:
        rating = str(item.get("rating", "")).strip().lower()
        if rating in counts:
            counts[rating] += 1
    return counts


def render_object_card(item: Dict[str, Any], index: int) -> None:
    object_name = item.get("object_name", f"Object {index}")
    condition = item.get("condition_summary", "No condition summary provided.")
    findings = item.get("findings", [])
    positives = item.get("positive_indicators", [])
    risks = item.get("risk_indicators", [])
    recommendations = item.get("recommendations", [])
    confidence = item.get("confidence", "Medium")
    rating = str(item.get("rating", "fair")).strip().lower()

    st.markdown(
        f"""
        <div class="object-card">
            <div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;">
                <div>
                    <div class="section-title">{object_name}</div>
                    <div class="muted">Confidence: {to_label(confidence)}</div>
                </div>
                <div>{rating_badge(rating)}</div>
            </div>
            <p class="muted" style="margin-top:12px;">{condition}</p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    col1, col2 = st.columns(2)
    with col1:
        st.write("Findings")
        st.write(findings if findings else ["No detailed findings provided."])
        st.write("Positive Indicators")
        st.write(positives if positives else ["No positive indicators identified."])
    with col2:
        st.write("Risk Indicators")
        st.write(risks if risks else ["No risk indicators identified."])
        st.write("Recommendations")
        st.write(recommendations if recommendations else ["No recommendations provided."])


def render_record_metadata(record: Dict[str, Any]) -> None:
    st.markdown(
        f"""
        <div class="record-card">
            <div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;">
                <div>
                    <div class="section-title">{record.get('applicant_name') or record.get('account_name') or 'Unnamed Applicant'}</div>
                    <div class="small">Record ID: {record.get('id')} | CI: {record.get('ci_submitter_name', 'Unknown')}</div>
                </div>
                <div>{status_badge(record.get('status', 'submitted_to_ao'))}</div>
            </div>
            <div class="small" style="margin-top:10px;">
                Template: {record.get('template_label') or 'Not selected'}<br/>
                Submitted by CI: {record.get('ci_submitted_at', 'N/A')}<br/>
                AO Generated: {record.get('ao_generated_at', 'N/A')}<br/>
                Sent to Officer: {record.get('submitted_to_officer_at', 'N/A')}
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_ci_dashboard(user: Dict[str, str]) -> None:
    if st.session_state.get("ci_clear_submit_notes"):
        st.session_state["ci_submit_notes"] = ""
        st.session_state["ci_clear_submit_notes"] = False

    my_records = list_records_for_user("ci", user["email"])
    pending_count = sum(1 for record in my_records if record.get("status") == "submitted_to_ao")
    sent_count = sum(1 for record in my_records if record.get("status") == "submitted_to_officer")

    with st.sidebar:
        st.subheader("Session")
        st.write(f"Signed in as `{user['name']}`")
        st.write("Role: `CI`")
        st.divider()
        render_metric("My Notes", str(len(my_records)), "All notes submitted by this CI account.")
        render_metric("Waiting AO", str(pending_count), "Notes currently queued for AO review.")
        render_metric("Sent Forward", str(sent_count), "Records already delivered to the Officer inbox.")
        if st.button("Sign Out", use_container_width=True):
            logout()

    st.markdown(
        """
        <div class="hero">
            <h1>CI Notes Submission</h1>
            <p>
                CI accounts only submit notes into the shared inventory. AO will review, select the
                correct PDRN format, generate the workbook, and forward the finished file to the Officer.
            </p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    tab_submit, tab_history = st.tabs(["Submit Notes", "My Submission History"])

    with tab_submit:
        st.text_area(
            "Paste CI notes here",
            key="ci_submit_notes",
            height=420,
            placeholder="Paste the full CI notes. AO will receive this in the inventory queue.",
        )
        if st.button("Submit Notes to AO Queue", type="primary", use_container_width=True):
            notes = st.session_state.get("ci_submit_notes", "").strip()
            if not notes:
                st.error("Please paste the CI notes before submitting.")
            else:
                record = create_ci_submission(notes, user)
                st.session_state["ci_clear_submit_notes"] = True
                st.success(f"Notes submitted successfully. Record ID: {record['id']}")
                st.rerun()

    with tab_history:
        if not my_records:
            st.info("No CI submissions yet.")
        for record in my_records:
            with st.expander(format_record_title(record)):
                render_record_metadata(record)
                st.markdown('<div class="section-title" style="margin-top:14px;">CI Notes</div>', unsafe_allow_html=True)
                st.markdown(f'<div class="note-box">{record.get("ci_notes", "")}</div>', unsafe_allow_html=True)


def render_record_form(prefix: str) -> None:
    with st.expander("Request Details", expanded=True):
        col1, col2, col3 = st.columns(3)
        with col1:
            st.text_input("Reference Number", key=f"{prefix}_reference_number")
            st.text_input("BPI Request Number", key=f"{prefix}_bpi_request_number")
            st.text_input("LOS Request Number", key=f"{prefix}_los_request_number")
        with col2:
            st.text_input("Requesting Officer / Dept", key=f"{prefix}_requesting_officer")
            st.text_input("Date / Time Inspected", key=f"{prefix}_date_time_inspected")
            st.text_input("Time of Visit", key=f"{prefix}_time_of_visit")
        with col3:
            st.text_input("Field Investigator", key=f"{prefix}_field_investigator")
            st.text_input("Submitted Date", key=f"{prefix}_submitted_date")
            st.text_input("Submitted Time", key=f"{prefix}_submitted_time")

    with st.expander("Subject and Family", expanded=True):
        col1, col2, col3 = st.columns(3)
        with col1:
            st.text_input("Account Name", key=f"{prefix}_account_name")
            st.text_input("Subject Last Name", key=f"{prefix}_subject_last_name")
            st.text_input("Subject First Name", key=f"{prefix}_subject_first_name")
            st.text_input("Subject Middle Name", key=f"{prefix}_subject_middle_name")
            st.text_input("Nickname", key=f"{prefix}_subject_nickname")
        with col2:
            st.text_input("Birthday / Age", key=f"{prefix}_subject_bday_age")
            st.text_input("Civil Status", key=f"{prefix}_subject_civil_status")
            st.text_input("Gender", key=f"{prefix}_subject_gender")
            st.text_input("Nationality", key=f"{prefix}_subject_nationality")
            st.text_input("Educational Attainment", key=f"{prefix}_subject_education")
        with col3:
            st.text_input("Employment Source", key=f"{prefix}_subject_employment")
            st.text_input("Business Source", key=f"{prefix}_subject_business")
            st.text_area("Dependents / Ages / School", key=f"{prefix}_dependents", height=124)

        spouse_col1, spouse_col2, spouse_col3 = st.columns(3)
        with spouse_col1:
            st.text_input("Spouse Last Name", key=f"{prefix}_spouse_last_name")
            st.text_input("Spouse First Name", key=f"{prefix}_spouse_first_name")
            st.text_input("Spouse Middle Name", key=f"{prefix}_spouse_middle_name")
        with spouse_col2:
            st.text_input("Spouse Birthday / Age", key=f"{prefix}_spouse_bday_age")
            st.text_input("Spouse Civil Status", key=f"{prefix}_spouse_civil_status")
            st.text_input("Spouse Nationality", key=f"{prefix}_spouse_nationality")
        with spouse_col3:
            st.text_input("Spouse Education", key=f"{prefix}_spouse_education")
            st.text_input("Spouse Employment", key=f"{prefix}_spouse_employment")
            st.text_input("Spouse Business", key=f"{prefix}_spouse_business")

    with st.expander("Address and Residence", expanded=True):
        col1, col2 = st.columns(2)
        with col1:
            st.text_area("Complete Address", key=f"{prefix}_complete_address", height=100)
            st.text_input("Present Address", key=f"{prefix}_present_address")
            st.text_input("Previous Address", key=f"{prefix}_previous_address")
            st.text_input("Province", key=f"{prefix}_province")
            st.text_input("Region", key=f"{prefix}_region")
            st.text_input("Contact Number", key=f"{prefix}_contact_number")
        with col2:
            st.text_input("Ownership", key=f"{prefix}_ownership")
            st.text_input("Length of Stay", key=f"{prefix}_length_of_stay")
            st.text_input("Type of Residence", key=f"{prefix}_type_of_residence")
            st.text_input("No. of Storey", key=f"{prefix}_no_of_storey")
            st.text_input("Classification", key=f"{prefix}_classification")
            st.text_input("House Condition", key=f"{prefix}_house_condition")

    with st.expander("Property and Environment", expanded=False):
        col1, col2, col3 = st.columns(3)
        with col1:
            st.text_input("Made Of", key=f"{prefix}_made_of")
            st.text_input("Appearance", key=f"{prefix}_appearance")
            st.text_input("Accessibility", key=f"{prefix}_accessibility")
            st.text_input("Neighborhood", key=f"{prefix}_neighborhood")
            st.text_input("Vehicles", key=f"{prefix}_vehicles")
        with col2:
            st.text_input("House Color", key=f"{prefix}_house_color")
            st.text_input("Gate Color", key=f"{prefix}_gate_color")
            st.text_input("Fence Color", key=f"{prefix}_fence_color")
            st.text_input("Interior", key=f"{prefix}_interior")
            st.text_input("Exterior", key=f"{prefix}_exterior")
        with col3:
            st.text_input("Parking", key=f"{prefix}_parking")
            st.text_input("Lot Area", key=f"{prefix}_lot_area")
            st.text_input("Floor Area", key=f"{prefix}_floor_area")
            st.text_input("Landmark", key=f"{prefix}_landmark")
            st.text_input("Corner", key=f"{prefix}_corner")

    with st.expander("Verification and Output", expanded=False):
        col1, col2 = st.columns(2)
        with col1:
            st.text_input("Utility Bills / IDs", key=f"{prefix}_utility_bills")
            st.text_input("Coordinates", key=f"{prefix}_coordinates")
            st.text_input("Ownership Verification", key=f"{prefix}_ownership_verification")
            st.text_input("Basis of Ownership Verification", key=f"{prefix}_basis_of_ownership_verification")
            st.text_input("Outcome", key=f"{prefix}_outcome")
        with col2:
            st.text_input("Living Condition", key=f"{prefix}_living_condition")
            st.text_input("Neighborhood Classification", key=f"{prefix}_neighborhood_classification")
            st.text_input("Area Definition", key=f"{prefix}_area_definition")
            st.text_input("Adverse Finding", key=f"{prefix}_adverse_finding")
            st.text_input("Nearest BDO Branch", key=f"{prefix}_nearest_bdo_branch")
            st.text_input("Distance to BDO / Landmark", key=f"{prefix}_bdo_distance")

        st.text_area("Remarks", key=f"{prefix}_remarks", height=180)
        st.text_area("Informants", key=f"{prefix}_informants", height=120)
        st.text_area("Main Informant", key=f"{prefix}_main_informant", height=90)


def render_ao_dashboard(user: Dict[str, str]) -> None:
    all_ao_records = list_records_for_user("ao", user["email"])
    queue_records = [record for record in all_ao_records if record.get("status") in {"submitted_to_ao", "generated_by_ao"}]
    sent_records = [record for record in all_ao_records if record.get("status") == "submitted_to_officer"]

    with st.sidebar:
        st.subheader("Session")
        st.write(f"Signed in as `{user['name']}`")
        st.write("Role: `AO`")
        st.divider()
        render_metric("Queue", str(len(queue_records)), "CI notes waiting for AO preparation or generation.")
        render_metric("BPI Ready", str(count_by_template(sent_records + queue_records, "bpi")), "Records currently using the BPI template.")
        render_metric("Maybank Ready", str(count_by_template(sent_records + queue_records, "maybank")), "Records currently using the Maybank template.")
        if st.button("Sign Out", use_container_width=True):
            logout()

    st.markdown(
        """
        <div class="hero">
            <h1>AO PDRN Workspace</h1>
            <p>
                Review CI notes from the inventory, choose the correct PDRN format, generate the workbook,
                and submit the finished file to the Officer inbox.
            </p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    tab_queue, tab_workspace, tab_sent = st.tabs(["Submission Queue", "PDRN Workspace", "Sent to Officer"])

    with tab_queue:
        metrics = st.columns(3)
        with metrics[0]:
            render_metric("Pending AO Review", str(sum(1 for record in queue_records if record.get("status") == "submitted_to_ao")), "Notes not yet generated into a workbook.")
        with metrics[1]:
            render_metric("Generated", str(sum(1 for record in queue_records if record.get("status") == "generated_by_ao")), "Workbook generated but not yet sent to Officer.")
        with metrics[2]:
            render_metric("Sent", str(len(sent_records)), "Records already submitted to the Officer inbox.")

        if not queue_records:
            st.info("No queued records for AO right now.")
        else:
            selected_id = st.selectbox(
                "Choose a record to review",
                options=[record["id"] for record in queue_records],
                format_func=lambda record_id: format_record_title(get_record(record_id) or {"id": record_id}),
                index=0,
            )
            selected_record = get_record(selected_id)
            if selected_record:
                render_record_metadata(selected_record)
                st.markdown('<div class="section-title" style="margin-top:14px;">CI Notes Preview</div>', unsafe_allow_html=True)
                st.markdown(f'<div class="note-box">{selected_record.get("ci_notes", "")}</div>', unsafe_allow_html=True)
                if st.button("Load Selected Record Into Workspace", type="primary", use_container_width=True):
                    load_record_to_workspace(selected_record)
                    st.success(f"Loaded record {selected_record['id']} into the AO workspace.")

    with tab_workspace:
        selected_record_id = st.session_state.get("ao_selected_record_id", "")
        selected_record = get_record(selected_record_id) if selected_record_id else None
        if not selected_record:
            st.info("Load a record from the queue first.")
        else:
            render_record_metadata(selected_record)
            left_col, right_col = st.columns([0.95, 1.25])
            with left_col:
                st.markdown('<div class="section-title">CI Notes</div>', unsafe_allow_html=True)
                st.markdown(f'<div class="note-box">{selected_record.get("ci_notes", "")}</div>', unsafe_allow_html=True)
            with right_col:
                st.markdown('<div class="section-title">AO Actions</div>', unsafe_allow_html=True)
                template_keys = list(TEMPLATE_OPTIONS.keys())
                current_template_key = st.session_state.get("ao_template_key", DEFAULT_TEMPLATE_KEY)
                if current_template_key not in template_keys:
                    current_template_key = DEFAULT_TEMPLATE_KEY
                template_key = st.selectbox(
                    "Choose PDRN template",
                    options=template_keys,
                    index=template_keys.index(current_template_key),
                    format_func=lambda key: TEMPLATE_OPTIONS[key]["label"],
                    key="ao_template_key",
                )
                template_upload = st.file_uploader(
                    "Optional custom template upload",
                    type=["xls", "xlsx"],
                    key="ao_template_upload",
                    help="Use this only when you want to override the default template file.",
                )
                action_cols = st.columns(3)
                with action_cols[0]:
                    if st.button("Autofill From Notes", use_container_width=True):
                        parsed = parse_ci_notes(selected_record.get("ci_notes", ""))
                        parsed["field_investigator"] = user["name"]
                        seed_form_state("ao", parsed)
                        st.success("AO form refreshed from the CI notes.")
                with action_cols[1]:
                    if st.button("Generate Workbook", type="primary", use_container_width=True):
                        record_data = collect_form_data("ao")
                        record_data["field_investigator"] = record_data.get("field_investigator") or user["name"]
                        record_data["requesting_officer"] = record_data.get("requesting_officer") or user["name"]
                        template_bytes = template_upload.getvalue() if template_upload else None
                        try:
                            file_bytes, base_filename = export_ci_to_template(
                                record_data,
                                template_key=template_key,
                                template_bytes=template_bytes,
                            )
                            output_name = f"{selected_record['id']}_{base_filename}"
                            output_path = save_export_copy(file_bytes, output_name)
                            st.session_state["ao_export_bytes"] = file_bytes
                            st.session_state["ao_export_name"] = output_name
                            st.session_state["ao_export_path"] = output_path
                            updated = update_record(
                                selected_record["id"],
                                {
                                    "status": "generated_by_ao",
                                    "parsed_data": record_data,
                                    "template_key": template_key,
                                    "template_label": TEMPLATE_OPTIONS[template_key]["label"],
                                    "ao_email": user["email"],
                                    "ao_name": user["name"],
                                    "ao_generated_at": datetime.now().isoformat(timespec="seconds"),
                                    "generated_file_name": output_name,
                                    "generated_file_path": output_path,
                                },
                            )
                            if updated:
                                st.success("Workbook generated and stored in the inventory.")
                        except Exception as exc:
                            st.error(f"Unable to generate workbook: {exc}")
                with action_cols[2]:
                    if st.button("Submit to Officer", use_container_width=True):
                        output_path = st.session_state.get("ao_export_path") or selected_record.get("generated_file_path", "")
                        if not output_path:
                            st.error("Generate the workbook first before sending it to the Officer.")
                        else:
                            record_data = collect_form_data("ao")
                            update_record(
                                selected_record["id"],
                                {
                                    "status": "submitted_to_officer",
                                    "parsed_data": record_data,
                                    "template_key": template_key,
                                    "template_label": TEMPLATE_OPTIONS[template_key]["label"],
                                    "ao_email": user["email"],
                                    "ao_name": user["name"],
                                    "generated_file_name": st.session_state.get("ao_export_name") or selected_record.get("generated_file_name", ""),
                                    "generated_file_path": output_path,
                                    "submitted_to_officer_at": datetime.now().isoformat(timespec="seconds"),
                                },
                            )
                            st.success("Record submitted to the Officer inbox.")
                            st.rerun()

                download_bytes = st.session_state.get("ao_export_bytes") or read_file_bytes(
                    st.session_state.get("ao_export_path") or selected_record.get("generated_file_path", "")
                )
                download_name = st.session_state.get("ao_export_name") or selected_record.get("generated_file_name", "")
                if download_bytes and download_name:
                    st.download_button(
                        "Download Current Workbook",
                        data=download_bytes,
                        file_name=download_name,
                        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        use_container_width=True,
                    )
                    st.caption(f"Saved copy: `{st.session_state.get('ao_export_path') or selected_record.get('generated_file_path', '')}`")

            render_record_form("ao")

    with tab_sent:
        if not sent_records:
            st.info("No records have been submitted to the Officer yet.")
        for record in sent_records:
            with st.expander(format_record_title(record)):
                render_record_metadata(record)
                file_bytes = read_file_bytes(record.get("generated_file_path", ""))
                if file_bytes:
                    st.download_button(
                        f"Download {record.get('generated_file_name', 'pdrn.xlsx')}",
                        data=file_bytes,
                        file_name=record.get("generated_file_name", "pdrn.xlsx"),
                        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        key=f"ao_download_{record['id']}",
                    )


def render_officer_analyzer(user: Dict[str, str]) -> None:
    company_name = st.text_input("Company Name", value="Your Company")
    officer_name = st.text_input("Senior Account Officer", value=user["name"])
    inspection_context = st.text_area(
        "Inspection Context",
        value=(
            "Assess visible objects, structures, and materials. Highlight quality issues such as "
            "rust, damage, rot, moisture, wear, poor maintenance, or strong overall condition."
        ),
        height=140,
    )
    strict_mode = st.checkbox("Use stricter quality ratings", value=True)

    uploaded_file = st.file_uploader(
        "Upload inspection image",
        type=["png", "jpg", "jpeg", "webp"],
        accept_multiple_files=False,
        help="Upload a clear inspection image of the property, gate, wood structure, vehicle, or asset.",
    )

    if not uploaded_file:
        st.info("Upload an image to begin the AI analysis.")
        return

    image_bytes = uploaded_file.getvalue()
    image = Image.open(BytesIO(image_bytes))

    preview_col, action_col = st.columns([1.1, 1.4])
    with preview_col:
        st.image(image, caption=uploaded_file.name, use_container_width=True)
    with action_col:
        render_metric("Officer", officer_name or "Not specified", "Current user running the image analysis.")
        render_metric("Strict Mode", "Enabled" if strict_mode else "Standard", "Conservative quality scoring when enabled.")
        analyze_clicked = st.button("Analyze Image", type="primary", use_container_width=True)

    if not analyze_clicked:
        return

    api_key = get_gemini_api_key()
    if not api_key:
        st.error("Missing `GEMINI_API_KEY`. Add it to `.env` or Streamlit secrets.")
        return

    with st.spinner("Analyzing image and evaluating object quality..."):
        result = analyze_image_with_gemini(
            api_key=api_key,
            image_bytes=image_bytes,
            image_mime_type=uploaded_file.type or "image/jpeg",
            company_name=company_name,
            officer_name=officer_name,
            inspection_context=inspection_context,
            strict_mode=strict_mode,
        )

    if result.get("error"):
        st.error(result["error"])
        return

    objects = normalize_objects(result)
    counts = summarize_objects(objects)
    overall_rating = str(result.get("overall_rating", "fair")).strip().lower()
    overall_summary = result.get("overall_summary", "No summary returned.")
    priority_risks = result.get("priority_risks", [])
    recommendations = result.get("overall_recommendations", [])
    detected_scene = result.get("scene_type", "General inspection")

    st.subheader("Executive Summary")
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        render_metric("Overall Rating", to_label(overall_rating), overall_summary)
    with col2:
        render_metric("Scene Type", detected_scene, "AI-estimated scene type from visible evidence.")
    with col3:
        render_metric("Objects Found", str(len(objects)), "Visible objects or structures analyzed.")
    with col4:
        critical_count = counts["very bad"] + counts["poor"]
        render_metric("Critical Issues", str(critical_count), "Objects flagged as very bad or poor.")

    st.subheader("Rating Distribution")
    dist_cols = st.columns(len(RATING_ORDER))
    for idx, rating in enumerate(RATING_ORDER):
        with dist_cols[idx]:
            render_metric(to_label(rating), str(counts[rating]), "Detected object count")

    if priority_risks:
        st.subheader("Priority Risks")
        for risk in priority_risks:
            st.warning(risk)

    if recommendations:
        st.subheader("Management Recommendations")
        for recommendation in recommendations:
            st.success(recommendation)

    st.subheader("Object-by-Object Analysis")
    if not objects:
        st.info("The AI did not return specific objects for this image.")
    for idx, item in enumerate(objects, start=1):
        render_object_card(item, idx)

    with st.expander("Raw JSON Result"):
        st.code(json.dumps(result, indent=2), language="json")


def render_officer_dashboard(user: Dict[str, str]) -> None:
    officer_records = list_records_for_user("officer", user["email"])

    with st.sidebar:
        st.subheader("Session")
        st.write(f"Signed in as `{user['name']}`")
        st.write("Role: `Officer`")
        st.divider()
        render_metric("PDRN Inbox", str(len(officer_records)), "Generated PDRN workbooks submitted by AO.")
        render_metric("BPI Files", str(count_by_template(officer_records, "bpi")), "Officer inbox items generated in BPI format.")
        render_metric("Maybank Files", str(count_by_template(officer_records, "maybank")), "Officer inbox items generated in Maybank format.")
        if st.button("Sign Out", use_container_width=True):
            logout()

    st.markdown(
        """
        <div class="hero">
            <h1>Officer Workspace</h1>
            <p>
                Review the generated PDRN workbooks submitted by AO and continue using the AI Image Analyzer
                for property and asset image assessments.
            </p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    tab_inbox, tab_analyzer = st.tabs(["PDRN Inbox", "AI Image Analyzer"])

    with tab_inbox:
        if not officer_records:
            st.info("The Officer inbox is currently empty.")
        for record in officer_records:
            with st.expander(format_record_title(record)):
                render_record_metadata(record)
                parsed = record.get("parsed_data", {})
                applicant = join_name(
                    parsed.get("subject_last_name", ""),
                    parsed.get("subject_first_name", ""),
                    parsed.get("subject_middle_name", ""),
                )
                st.write(f"Applicant: `{applicant or parsed.get('account_name', 'Unknown')}`")
                st.write(f"AO: `{record.get('ao_name', 'Unknown AO')}`")
                st.write(f"Template: `{record.get('template_label', 'Unknown Template')}`")
                st.write(f"Address: {parsed.get('complete_address', 'No address provided')}")
                st.markdown('<div class="section-title" style="margin-top:12px;">CI Notes</div>', unsafe_allow_html=True)
                st.markdown(f'<div class="note-box">{record.get("ci_notes", "")}</div>', unsafe_allow_html=True)
                file_bytes = read_file_bytes(record.get("generated_file_path", ""))
                if file_bytes:
                    st.download_button(
                        f"Download {record.get('generated_file_name', 'pdrn.xlsx')}",
                        data=file_bytes,
                        file_name=record.get("generated_file_name", "pdrn.xlsx"),
                        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        key=f"officer_download_{record['id']}",
                    )

    with tab_analyzer:
        render_officer_analyzer(user)


def main() -> None:
    inject_styles()
    init_session_state()

    user = st.session_state.get("auth_user")
    if not user:
        render_login_page()
        return

    if user["role"] == "ci":
        render_ci_dashboard(user)
        return
    if user["role"] == "ao":
        render_ao_dashboard(user)
        return
    render_officer_dashboard(user)


if __name__ == "__main__":
    main()
